### ISSUE TITLE
the app will be closed when you enter EA8DKV only

### ISSUE THREAD

**Issue by dc5ly** [ham2k/app-polo#26]
the app will be closed when you enter EA8DKV only this Callsign. The Version is 0.7.8 All other Callsign´s will work great only this one does not work.

**Comment by kwirk** [comment]
This may have been fixed with ee02b938a.

You can test via [the *unstable* track](https://polo.ham2k.com/docs/developer-mode/), or wait for next *stable* release.

**Comment by sd** [comment]
I believe this issue has been fixed already. Please reopen the ticket if it still happens on 0.7.9
