### ISSUE TITLE
Notes vs Comments

### ISSUE THREAD

**Issue by jeffkowalski** [ham2k/app-polo#31]
I'm curious about the choice of "Notes" rather than "Comments" for the free-form text entry in a qso.
I had become accustomed to FLE-style use of the Comments field, and my online logs all use that.
Is there a way to allow a choice of which to use?
(If not, I can always post-process the adif file)

**Comment by sd** [comment]
From the ADIF spec, "Notes" is for information of interest to the logging operator, while "Comments" is information of interest to the contacted operator. I had to pick one so I went with the one that made most sense to most people.

I could make it a configurable setting, but I'm afraid it would be confusing for pretty much everybody.

Or maybe the easiest solution is to put the same notes on both fields?

**Comment by jeffkowalski** [comment]
I would refer you to two other popular items:

1)  FLE (Fast Log Entry).  There, text in angle-brackets is converted to an ADIF Comment (not a Note) for a QSO.  In fact, there doesn't appear to be a way to enter a Note.  From that, I infer that Comments are the most common method of storing additional information for a specific contact (QSO), in practice.
See https://df3cb.com/fle/documentation/#qsos

2) QRZ.com, a commonly used logbook, displays Comments rather than Notes by default.  Again, more the more common practice.
