### ISSUE TITLE
Fields for entry of numerical values should switch to numerical keypad

### ISSUE THREAD

**Issue by DocViper666** [ham2k/app-polo#51]
Maybe only an issue on Android (?) but for the entry of numerical values for:

- RST
- Frequency

the keyboard should/could switch from the full keyboard to just the numerical (number keypad) version.

Maybe more an issue on phones.
https://reflector.sota.org.uk/uploads/db9433/optimized/3X/a/3/a3d803a6e93539c63256b1a062f4193dd7eefcb2_2_225x500.png

Thanks
___
73 de Joe, OE5JFE

**Comment by sd** [comment]
I considered doing this, but found that the switching of keyboard modes in between fields was a bit jarring. 

I might reconsider and try it again soon.

**Comment by rmx-it** [comment]
Yes, please.
This was the first thing I found annoying after first trying PoLo.
