### ISSUE TITLE
Offline names of people involved in SOTA

### ISSUE THREAD

**Issue by DocViper666** [ham2k/app-polo#54]
I tried to convert the names of SOTA operators that are available for another well known portable logging tool to be included in PoLo via the custom 'hams of note.txt' feature:

The original csv is available here: https://hb9sota.ch/wp-content/uploads/2024/06/names.csv
 
And my conversion with a summit icon here:
https://spotoe.docviper.net/SOTA%20-%20Hams%20of%20Note.txt

Looks like 72755 callsigns are too much for the system? Or any specific encoding required? Looks like the emoji are ANSI
Stable mobile phone service is not everywhere so this is additionally useful to the QRZ lookup.

EDIT / UPDATE:
2 days later when starting it took a bit longer but now it looks like all the SOTA callsigns are available with the summit symbol. 
So I guess the process of loading / managing the calls is having troubles?

**Comment by sd** [comment]
The file has to be encoded in UTF-8.

The "callsign notes" system was not designed to handle 72k entries, but as long as your device has enough memory, it should work.

Notes are refreshed automatically once a day, which might be why the app took longer to start.
