### ISSUE TITLE
activity export for sota fails

### ISSUE THREAD

**Issue by pxforti** [ham2k/app-polo#55]
Hi,

I just did a POTA, SOTA, WWFF activation. POTA export uploaded fine to POTA site. SOTA export failed with the following errors:

Any idea why it's failing?

FROM THE SOTADATA UPLOAD SITE:

The following errors were found in your file:
Line 11 has insufficient fields
Error on Line 11: No V2 header found
Line 47 has insufficient fields
Error on Line 47: No V2 header found
Line 48 has insufficient fields
Error on Line 48: No V2 header found
Line 51 has insufficient fields
Error on Line 51: No V2 header found

Here is a copy of the POLO log file:

ADIF for K7GUD: SOTA at W7Y/TT-172 - 7260 on 2024-08-21 
<ADIF_VER:5>3.1.4
<PROGRAMID:21>Ham2K Portable Logger
<PROGRAMVERSION:6>24.8.0
<EOH>
<CALL:6>DL8DXL <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>162500 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>JO61wf <MY_GRIDSQUARE:6>DN43vw <NAME:10>Fred Grimm <DXCC:3>230 <QTH:15>01936 Laussnitz <CQZ:2>14 <ITUZ:2>28 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>S57S <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>162600 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>JN76jb <MY_GRIDSQUARE:6>DN43vw <NAME:16>Aleksander Zagar <DXCC:3>499 <QTH:16>Si-1281 Kresnice <CQZ:2>15 <ITUZ:2>28 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>N4DH <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>162700 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>FM06ce <MY_GRIDSQUARE:6>DN43vw <NAME:14>Dean C. Wilson <DXCC:3>291 <QTH:10>Greensboro <STATE:2>NC <CQZ:1>5 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>F4WBN <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>162715 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>IN93hl <MY_GRIDSQUARE:6>DN43vw <NAME:23>Christian Saint-Arroman <DXCC:3>227 <QTH:6>Urcuit <CQZ:2>14 <ITUZ:2>27 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:6>WB6POT <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>162800 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CM99mb <MY_GRIDSQUARE:6>DN43vw <NAME:19>Peter R. Woodmansee <DXCC:3>291 <QTH:8>San Jose <STATE:2>CA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>K8HF <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>162845 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EN80qs <MY_GRIDSQUARE:6>DN43vw <NAME:23>Harry M. Frietchen, III <DXCC:3>291 <QTH:9>Mansfield <STATE:2>OH <CQZ:1>4 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>W6TDX <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>162930 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CN73sc <MY_GRIDSQUARE:6>DN43vw <NAME:24>Christopher J. Bottalico <DXCC:3>291 <QTH:6>Bandon <STATE:2>OR <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>K6YK <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163015 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CM97jw <MY_GRIDSQUARE:6>DN43vw <NAME:11>John W. Lee <DXCC:3>291 <QTH:8>Stockton <STATE:2>CA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>N4LAG <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163100 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM85sn <MY_GRIDSQUARE:6>DN43vw <NAME:19>Lynn A. "Andy" Goss <DXCC:3>291 <QTH:9>Asheville <STATE:2>NC <CQZ:1>5 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>K2JB <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163145 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM85qm <MY_GRIDSQUARE:6>DN43vw <NAME:21>Jimmy D. "Dean" Blair <DXCC:3>291 <QTH:9>Asheville <STATE:2>NC <CQZ:1>5 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>AK5SD <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163230 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM10bo <MY_GRIDSQUARE:6>DN43vw <NAME:15>Scott T. Dupuie <DXCC:3>291 <QTH:7>Leander <STATE:2>TX <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>W5ODS <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163315 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM26db <MY_GRIDSQUARE:6>DN43vw <NAME:13>Gary C. Burch <DXCC:3>291 <QTH:12>Broken Arrow <STATE:2>OK <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:6>IW2NXI <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163400 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>JN55ee <MY_GRIDSQUARE:6>DN43vw <NAME:16>Graziano (Grace) <DXCC:3>248 <QTH:8>Asola MN <CQZ:2>15 <ITUZ:2>28 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>K8ITU <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163445 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM88si <MY_GRIDSQUARE:6>DN43vw <NAME:23>Wendell R. "Ray" Messer <DXCC:3>291 <QTH:10>Huntington <STATE:2>WV <CQZ:1>4 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>WN1G <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163530 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM64nv <MY_GRIDSQUARE:6>DN43vw <NAME:13>Linda J. Haft <DXCC:3>291 <QTH:6>Athens <STATE:2>AL <CQZ:1>5 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>W4JL <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163615 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM95fm <MY_GRIDSQUARE:6>DN43vw <NAME:23>David W. "Dave" Ledford <DXCC:3>291 <QTH:8>Lawndale <STATE:2>NC <CQZ:1>5 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <SIG:4>WWFF <SIG_INFO:8>KFF-6812 <EOR>
<CALL:4>K6EL <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163700 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CM87ss <MY_GRIDSQUARE:6>DN43vw <NAME:16>Elliott M. Pisor <DXCC:3>291 <QTH:13>San Francisco <STATE:2>CA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <SOTA_REF:9>W6/NC-423 <EOR>
<CALL:4>W6DT <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>163745 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CM98is <MY_GRIDSQUARE:6>DN43vw <NAME:17>Wayne E. Stilwell <DXCC:3>291 <QTH:12>Meadow Vista <STATE:2>CA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>OM5TX <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>164400 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>JN97bx <MY_GRIDSQUARE:6>DN43vw <NAME:11>Jozef Botos <DXCC:3>504 <QTH:10>Nove Zamky <CQZ:2>15 <ITUZ:2>28 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>W5GDW <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>164400 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM95li <MY_GRIDSQUARE:6>DN43vw <NAME:13>Gary D. Whitt <DXCC:3>291 <QTH:11>Mount Holly <STATE:2>NC <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>OM5TX <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>164500 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>JN97bx <MY_GRIDSQUARE:6>DN43vw <NAME:11>Jozef Botos <DXCC:3>504 <QTH:10>Nove Zamky <CQZ:2>15 <ITUZ:2>28 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>N4MJ <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>164600 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM56nk <MY_GRIDSQUARE:6>DN43vw <NAME:13>Glenn R. Snow <DXCC:3>291 <QTH:12>South Fulton <STATE:2>TN <CQZ:1>5 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>NA2MM <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>164700 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>FN30jr <MY_GRIDSQUARE:6>DN43vw <NAME:16>Owen J. Monaghan <DXCC:3>291 <QTH:5>Islip <STATE:2>NY <CQZ:1>5 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>W0MNA <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>165300 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM29mj <MY_GRIDSQUARE:6>DN43vw <NAME:15>Gary L. Auchard <DXCC:3>291 <QTH:11>Leavenworth <STATE:2>KS <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>W0ERI <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>165300 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM29mj <MY_GRIDSQUARE:6>DN43vw <NAME:17>Martha S. Auchard <DXCC:3>291 <QTH:11>Leavenworth <STATE:2>KS <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>K0HJ <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>165400 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EN23be <MY_GRIDSQUARE:6>DN43vw <NAME:22>Delmar E. "Del" Spronk <DXCC:3>291 <QTH:7>Sheldon <STATE:2>IA <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>OH1MM <MODE:2>CW <BAND:4>160m <FREQ:8>1.807700 <QSO_DATE:8>20240821 <TIME_ON:6>165400 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>KP01tm <MY_GRIDSQUARE:6>DN43vw <NAME:11>Pasi Alanko <DXCC:3>224 <QTH:4>Pori <CQZ:2>15 <ITUZ:2>18 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>KN6MN <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>165500 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM43ao <MY_GRIDSQUARE:6>DN43vw <NAME:12>Bruce Toback <DXCC:3>291 <QTH:7>Phoenix <STATE:2>AZ <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>KF6HI <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>165600 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EN61lm <MY_GRIDSQUARE:6>DN43vw <NAME:17>Brian D. Hamerski <DXCC:3>291 <QTH:10>Valparaiso <STATE:2>IN <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>KC5BG <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>165700 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM86qd <MY_GRIDSQUARE:6>DN43vw <NAME:25>Michael L. "Mike" Emerson <DXCC:3>291 <QTH:7>Chuckey <STATE:2>TN <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>NT6E <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>165800 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM03tu <MY_GRIDSQUARE:6>DN43vw <NAME:15>Jon M. Kuroyama <DXCC:3>291 <QTH:8>Torrance <STATE:2>CA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>N8RQX <MODE:2>CW <BAND:3>20m <FREQ:9>14.063700 <QSO_DATE:8>20240821 <TIME_ON:6>170000 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM79wc <MY_GRIDSQUARE:6>DN43vw <NAME:15>John P. Fischer <DXCC:3>291 <QTH:7>Batavia <STATE:2>OH <CQZ:1>4 <ITUZ:1>8 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>WW7D <MODE:2>CW <BAND:3>20m <FREQ:9>14.063700 <QSO_DATE:8>20240821 <TIME_ON:6>170200 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CN87wq <MY_GRIDSQUARE:6>DN43vw <NAME:16>Darryl J. Holman <DXCC:3>291 <QTH:7>Redmond <STATE:2>WA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>WX7OR <MODE:2>CW <BAND:3>20m <FREQ:9>14.063700 <QSO_DATE:8>20240821 <TIME_ON:6>170400 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CN85pl <MY_GRIDSQUARE:6>DN43vw <NAME:26>Jeffrey A. "Jeff" McKinnis <DXCC:3>291 <QTH:8>Portland <STATE:2>OR <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>KE6MT <MODE:2>CW <BAND:3>20m <FREQ:9>14.063700 <QSO_DATE:8>20240821 <TIME_ON:6>170600 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CM97ah <MY_GRIDSQUARE:6>DN43vw <NAME:12>Rex J. Vokey <DXCC:3>291 <QTH:8>Campbell <STATE:2>CA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>NU7Y <MODE:2>CW <BAND:3>20m <FREQ:9>14.063700 <QSO_DATE:8>20240821 <TIME_ON:6>170615 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM42lj <MY_GRIDSQUARE:6>DN43vw <NAME:18>Quinton A. Gleason <DXCC:3>291 <QTH:10>Oro Valley <STATE:2>AZ <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>WU7H <MODE:2>CW <BAND:3>20m <FREQ:9>14.063700 <QSO_DATE:8>20240821 <TIME_ON:6>170700 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CN87us <MY_GRIDSQUARE:6>DN43vw <NAME:22>Joshua J. "Josh" Gibbs <DXCC:3>291 <QTH:16>Lake Forest Park <STATE:2>WA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>W7VD <MODE:2>CW <BAND:3>30m <FREQ:9>10.114000 <QSO_DATE:8>20240821 <TIME_ON:6>170800 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM09dj <MY_GRIDSQUARE:6>DN43vw <NAME:19>Robert H. Dickerson <DXCC:3>291 <QTH:4>Reno <STATE:2>NV <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>NU7A <MODE:2>CW <BAND:3>30m <FREQ:9>10.114000 <QSO_DATE:8>20240821 <TIME_ON:6>171200 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>CN97qo <MY_GRIDSQUARE:6>DN43vw <NAME:21>Howard "Bren" Brenner <DXCC:3>291 <QTH:11>Leavenworth <STATE:2>WA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>K7DNE <MODE:2>CW <BAND:3>30m <FREQ:9>10.114000 <QSO_DATE:8>20240821 <TIME_ON:6>171300 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DN17gq <MY_GRIDSQUARE:6>DN43vw <NAME:14>Daren N. Ellis <DXCC:3>291 <QTH:7>Spokane <STATE:2>WA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>AA7DK <MODE:2>CW <BAND:3>30m <FREQ:9>10.114000 <QSO_DATE:8>20240821 <TIME_ON:6>171400 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM45de <MY_GRIDSQUARE:6>DN43vw <NAME:17>Dennis R. Kimbell <DXCC:3>291 <QTH:9>Flagstaff <STATE:2>AZ <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>AD0WB <MODE:2>CW <BAND:3>30m <FREQ:9>10.114000 <QSO_DATE:8>20240821 <TIME_ON:6>171500 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM79lp <MY_GRIDSQUARE:6>DN43vw <NAME:29>Wilfred M. "Mike" Bywater, II <DXCC:3>291 <QTH:6>Denver <STATE:2>CO <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>AC7P <MODE:2>CW <BAND:3>30m <FREQ:9>10.113000 <QSO_DATE:8>20240821 <TIME_ON:6>171900 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EL09xt <MY_GRIDSQUARE:6>DN43vw <NAME:22>Creath D. Fletcher, Jr <DXCC:3>291 <QTH:13>New Braunfels <STATE:2>TX <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <SOTA_REF:10>W0C/FR-194 <EOR>
<CALL:4>AE7I <MODE:2>CW <BAND:3>20m <FREQ:9>14.059000 <QSO_DATE:8>20240821 <TIME_ON:6>172300 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM09bl <MY_GRIDSQUARE:6>DN43vw <NAME:14>Craig M. Sande <DXCC:3>291 <QTH:4>Reno <STATE:2>NV <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <SOTA_REF:9>W6/CN-005 <EOR>
<CALL:5>W7DLZ <MODE:2>CW <BAND:3>20m <FREQ:9>14.059000 <QSO_DATE:8>20240821 <TIME_ON:6>172700 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM09bq <MY_GRIDSQUARE:6>DN43vw <NAME:14>Derek J. Lentz <DXCC:3>291 <QTH:4>Reno <STATE:2>NV <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <SOTA_REF:9>W6/CN-005 <EOR>
<CALL:5>N0DNF <MODE:2>CW <BAND:3>40m <FREQ:8>7.033000 <QSO_DATE:8>20240821 <TIME_ON:6>173700 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DN32sx <MY_GRIDSQUARE:6>DN43vw <NAME:31>William J. "Bill" Skerjanc, 760 <DXCC:3>291 <QTH:9>Pocatello <STATE:2>ID <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:4>W5CU <MODE:2>CW <BAND:3>20m <FREQ:9>14.057000 <QSO_DATE:8>20240821 <TIME_ON:6>174200 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>EM15gq <MY_GRIDSQUARE:6>DN43vw <NAME:13>Sam C. Sitton <DXCC:3>291 <QTH:6>Edmond <STATE:2>OK <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <SOTA_REF:10>WOC/SP-110 <EOR>
<CALL:6>KE5AKL <MODE:2>CW <BAND:3>20m <FREQ:9>14.063000 <QSO_DATE:8>20240821 <TIME_ON:6>174700 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM65rc <MY_GRIDSQUARE:6>DN43vw <NAME:16>Michael M. Walsh <DXCC:3>291 <QTH:11>Albuquerque <STATE:2>NM <CQZ:1>4 <ITUZ:1>7 <MY_SOTA_REF:10>W7Y/TT-172 <EOR>
<CALL:5>AJ6CL <MODE:2>CW <BAND:3>20m <FREQ:9>14.063000 <QSO_DATE:8>20240821 <TIME_ON:6>175200 <RST_RCVD:3>599 <RST_SENT:3>599 <STATION_CALLSIGN:5>K7GUD <GRIDSQUARE:6>DM04ne <MY_GRIDSQUARE:6>DN43vw <NAME:13>Martin Hickey <DXCC:3>291 <QTH:13>Thousand Oaks <STATE:2>CA <CQZ:1>3 <ITUZ:1>6 <MY_SOTA_REF:10>W7Y/TT-172 <SOTA_REF:9>W6/CT-025 <EOR>

**Comment by DocViper666** [comment]
The V2 header exists only in SOTA csv files.

You need to upload the adif also using the adif upload feature on sotadata.

**Comment by pxforti** [comment]
OK. Thanks. I'm so used to uploading CSV, I didn't think of it.
