### ISSUE TITLE
Optimize screen layout also for phones

### ISSUE THREAD

**Issue by DocViper666** [ham2k/app-polo#57]
Please make it possible to optimize screen real estate for typical outdoor phones screen sizes (854×480 px) 

This should be of course optional as user preferences vary.

- QSO time: Make it only Hour:Minute HH:MM (no need for seconds and the trailing 'z' )
- QSO rates and statistics are relevant for contesting but not for SOTA or other activities

Thanks a lot

**Comment by kwirk** [comment]
I'd agree on dropping the seconds, as not that useful to me either. 

The QSO stats are replaced with lookup info when callsign is inputted so not much space to save there, and QSO stats seem like a good placeholder.

**Comment by Marzogh** [comment]
I third the idea of dropping the seconds, but I find the QSO stats are very useful midactivation when I can quickly check how many QSOs I have in total (i.e., have I activated the park or not?) and if the rate of QSOs is dropping, its my indicator to respot myself / move frequencoes, so I'd vote to keep that feature as is.

**Comment by kwirk** [comment]
Seconds aren't displayed on my phone anymore +1

**Comment by DocViper666** [comment]
Issue solved in commit 
https://github.com/ham2k/app-polo/commit/97728a889039b75858f97ea4de5f7a97d43a51a3

Thank you!
73 Joe, OE5JFE
