### ISSUE TITLE
[Feature Request] - Save the app's logs & settings in the cloud to enable sharing between devices

### ISSUE THREAD

**Issue by Marzogh** [ham2k/app-polo#59]
I use multiple (iOS & Android) devices during the course of my day and it would be wonderful if the app's database location could be in the 'cloud' in a way that is shareable between apps running on different devices.

 For example, simply saving the database in iCloud would enable my iPad and iPhone apps to stay in sync. Sync issues could be resolved by locking a file from being opened on a second device, till it is closed on the first.

If this works, then perhaps the database location could be user selectable? That would let me put the database on Google Drive / Dropbox / OneDrive and sync across platforms?

TIA!

**Comment by sd** [comment]
We're working on a backup and sync service.
