### ISSUE TITLE
[Feature request] User defined spot comment

### ISSUE THREAD

**Issue by DocViper666** [ham2k/app-polo#60]
Currently the Default Spot comment is set to 

> 'QRV with Ham2K PoLo'
at
src/screens/OperationScreens/OpLoggingTab/components/LoggingPanel/SecondaryExchangePanel/SpotterControl.jsx

Please make this **comment message user defined** e.g. via the General Settings or the Spot menu.

Best case make variables available to be added to the comment message like:
**%locator** : Would add the 6-digit maidenhead locator into the comment
**%allmyref** : Would add all the references (SOTA, POTA, FF) into the comment one after the other
**%myref** :  Would add the first references into the comment
**%op** :  Would add the name of the operator (that would also need become a setting)
**%mycall** : Would add the station callsign (a bit redundant but why not)

So one could make something like:

```
Joe QRV from %myref at %locator
Joe QRV from OE/OO-001 at JN67tl

```
or

```
QRV from %allmyref
QRV from OE/OO-254 AT-0042 OEFF-0004
```

Note: Some logging tools parse the details for awards from the comment messages so that might be a positive side effect for the chasers.

Thanks for all the work! 73 de Joe, OE5JFE

**Comment by sd** [comment]
Closing this issue because we're discontinuing the use of github issues to track these.  Please go to https://forums.ham2k.com and open a new topic.
