### ISSUE TITLE
[Bug] Autoformating of reference sometimes fails

### ISSUE THREAD

**Issue by DocViper666** [ham2k/app-polo#62]
I really like that when entering a S2S (or most likely also other types of references) one does normally not need to enter slash or dashes.
But it happens quite often that the auto formating goes wrong.

I could not find a pattern on references that fail or work. I have the feeling it might be the same issue like the "to quick" lookup of callsigns where the last char gets ignored.
Maybe a threading issues between UI and background tasks?

**Comment by sd** [comment]
The November release has some performance improvements that hopefuly fix these issues.

Please reopen this issue if you still see this happen.
