### ISSUE TITLE
Text field focus problem when switching to app on macOS

### ISSUE THREAD

**Issue by ptsmonteiro** [ham2k/app-polo#71]
When logging on macOS, I find myself switching between desktops. When going back to the app, I've noticed that even if the cursor is blinking on the text field, when I use the keyboard to type it does nothing. I have to click the field before to be able to type on it.

**Comment by sd** [comment]
Closing this issue because we're discontinuing the use of github issues to track these.  Please go to https://forums.ham2k.com and open a new topic.
