### ISSUE TITLE
Feature Request: QRZ Logbook Synchronization

### ISSUE THREAD

**Issue by sonyccd** [ham2k/app-polo#76]
# Feature Request: QRZ Logbook Synchronization

**Issue:** Add Automatic QRZ Logbook Syncing for Specific Operations in Polo Amateur Radio Logging App

## Summary
This feature will allow users of the Polo Amateur Radio Logging app to automatically upload their logs to the QRZ website using the QRZ API. Users will be able to sync specific operations (log files) within Polo to a designated logbook on QRZ. Additionally, this feature will offer real-time sync status updates, error notifications, and the ability to automatically append new entries to the logbook upon changes in the Polo log file.

---

### 1. QRZ API Integration and Authentication
   - **Authentication**: Users will need to enter QRZ credentials or an API token in Polo to connect to the QRZ API.
   - **Session Management**: Implement a session-based token system if possible to avoid repeated authentication requests. QRZ sessions are typically initiated through a **login** request, which returns a session key to be used in subsequent API calls.
   - **API Endpoint for Authentication**:  
     - **Login**: `https://logbook.qrz.com/api` (POST) with parameters:
       - `username` (QRZ username)
       - `password` (QRZ password)
     - **Session Key**: The QRZ API returns a session key upon successful login, which should be used for further API interactions.

### 2. Logbook Selection and Sync Settings
   - **Per-Operation Logbook Selection**: In Polo, users can select a QRZ logbook from a dropdown within each operation’s settings.
   - **Automatic Sync Toggle**: Include an option for users to enable or disable automatic syncing for each operation. If enabled, new log entries will automatically append to the QRZ logbook whenever added in Polo.
   - **Settings UI**: Provide a dedicated "QRZ Sync" tab in each operation’s settings, showing:
     - **Logbook Selection Dropdown**: Choose which QRZ logbook to sync to.
     - **Automatic Sync Toggle**: Enable or disable auto-sync.
     - **Manual Sync Button**: Allow users to initiate a manual sync at any time.

### 3. Automatic and Manual Sync Capabilities
   - **Initial Full Sync**: Upon first setup, the operation log should fully upload to the selected QRZ logbook.
   - **Incremental Sync**: New entries will be automatically appended to the QRZ logbook whenever the operation log is updated. Use Polo’s change detection to identify and upload only the new entries.
   - **Manual Sync Option**: If users prefer manual syncing, provide a button to push all unsynced entries to QRZ.
   - **API Endpoint for Log Upload**:
     - **Log Add**: `https://logbook.qrz.com/api/logbook_upload` (POST) with parameters:
       - `session_key`: (session token)
       - `log_entry`: (log data to upload in ADIF format or similar)

### 4. Sync Status and Error Handling
   - **Real-Time Status Indicator**:
     - Display a sync status next to each operation linked to a QRZ logbook:
       - “Sync Successful” (last sync date and time)
       - “Sync Pending” (for logs with changes awaiting upload)
       - “Sync in Progress” (during an active sync)
     - **Error Notification**: If any errors occur, an error message should appear in the sync status area, specifying the type of error (e.g., "Authentication Failed" or "API Timeout") with guidance for resolution.
   - **Retry Mechanism**: Automatically retry failed syncs up to a specified limit or allow users to manually retry.

### 5. Error Logging and Notifications
   - **Error Types and Handling**:
     - **Authentication Errors**: Prompt the user to re-enter credentials if authentication fails.
     - **Rate Limiting/Throttling**: Notify the user if QRZ’s rate limits are exceeded and pause sync attempts.
     - **API Errors**: Log detailed error codes for diagnostics and, where possible, present user-friendly guidance.
   - **User Feedback on Errors**:
     - Display error pop-ups or inline messages with error descriptions and steps for resolution.
     - In case of repeated errors, suggest checking API connection settings or contacting support.

---

## QRZ API Endpoints (Based on QRZ's Standard Logbook API)

Here's an overview of QRZ API endpoints you would typically use for logbook synchronization. (Note: Please verify endpoint details and API availability with QRZ documentation, as their API policies may have changed.)

1. **Authentication/Login**
   - **Endpoint**: `https://logbook.qrz.com/api`
   - **Method**: POST
   - **Parameters**:
     - `username`: QRZ user’s login username
     - `password`: QRZ password
   - **Response**: Returns a session key used for other API requests.

2. **Logbook Upload**
   - **Endpoint**: `https://logbook.qrz.com/api/logbook_upload`
   - **Method**: POST
   - **Parameters**:
     - `session_key`: Session token obtained from login
     - `log_entry`: Log entry data formatted as ADIF (Amateur Data Interchange Format), which is the preferred format for QRZ log uploads.
   - **Response**: Returns a success or error status with details if the upload fails.

3. **Logbook Query (Optional)**
   - **Endpoint**: `https://logbook.qrz.com/api/logbook_query`
   - **Method**: GET
   - **Parameters**:
     - `session_key`: Session token
     - `query`: Specific query for retrieving log data (e.g., date range, callsign).
   - **Response**: Returns data matching the query, which can help verify existing logs and ensure new entries don’t duplicate previously uploaded data.

4. **Logout (End Session)**
   - **Endpoint**: `https://logbook.qrz.com/api/logbook_logout`
   - **Method**: POST
   - **Parameters**:
     - `session_key`: Session token to be invalidated.
   - **Response**: Confirms session termination.

---

## Additional Development Notes

- **Rate Limits**: Be mindful of QRZ’s rate limits on API requests to avoid excessive calls, especially in cases of high user activity or frequent log updates.
- **ADIF Formatting**: Polo should format log entries to comply with the ADIF standard, as QRZ prefers ADIF for data interoperability.
- **Data Privacy and Security**: Ensure all user credentials and session tokens are securely handled and encrypted, following best practices for sensitive data.

**Comment by sonyccd** [comment]
This needs to built as an injector that can support other logging systems such a as log book of the world etc

**Comment by sd** [comment]
Closing this issue because we're discontinuing the use of github issues to track these.  Please go to https://forums.ham2k.com
